config/routes.rb
Misesajour::Application.routes.draw do
  resources :followers

  get 'paypal/success' => 'private#paypal_ok'
  get 'paypal/failed' => 'private#paypal_failed'

  resources :rt_twitts, :only => [:show, :create, :new, :update]

  get "dashboard" => "private#dashboard", :as => :dashboard

  resources :user_twitters

  resources :rss_items

  resources :rss_providers

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}, path: ''
  get "pricing" => 'public#pricing', :as => :pricing_en
  get "tarifs"  => 'public#pricing', :as => :pricing_fr
  root :to => 'public#index'
  match "*a" => redirect('/')
end

app/models/user_twitter.rb
class UserTwitter < ActiveRecord::Base
  belongs_to :user
  has_many :rss_providers
  has_many :followers
  has_many :rt_twitts
  attr_accessible :image_url, :provider, :public_token, :twitter_secret_token, :twitter_token, :uid, :username

  def get_follower
    @client = Twitter::Client.new(:oauth_token => self.twitter_token, :oauth_token_secret => self.twitter_secret_token)
    @client.followers.each do |follow|
      self.save_follower_info(follow, true)
    end
  end

  def save_follower_info(follow, my_follower)
    self.followers.create(
      :follow_request_send => follow.attrs[:follow_request_sent],
      :followers_count => follow.attrs[:followers_count],
      :following => follow.attrs[:following],
      :friends_count => follow.attrs[:friends_count],
      :twitter_id => follow.attrs[:id],
      :lang => follow.attrs[:lang],
      :last_tweet_date => follow.attrs[:status][:created_at],
      :name => follow.attrs[:name],
      :screen_name => follow.attrs[:screen_name],
      :status_count => follow.attrs[:statuses_count],
      :url => follow.attrs[:url],
      :follow_user => my_follower
    )
  end

  def get_follower_of_follower
    @client = Twitter::Client.new(:oauth_token => self.twitter_token, :oauth_token_secret => self.twitter_secret_token)
    self.followers.where("last_import<NOW() or ISNULL(last_import)").order('followers_count DESC').limit(5).each do |followed|
      @client.followers(followed.twitter_id).each do |follow|
        self.save_follower_info(follow, false)
      end
    end
  end
end

app/controllers/user_twitters_controller.rb
class UserTwittersController < ApplicationController
  layout 'private'
  before_filter :check_allowed, :only => [:new, :create]

  def check_allowed
    redirect_to dashboard_path if !current_user.can_add_account
  end

  # GET /user_twitters
  # GET /user_twitters.json
  def index
    @user_twitters = current_user.user_twitters.all

    if params[:src]=='ajax'
      render 'index', :layout => false
    else
      render 'index'
    end
  end

  # GET /user_twitters/1
  # GET /user_twitters/1.json
  def show
    @user_twitter = UserTwitter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_twitter }
    end
  end

  # GET /user_twitters/new
  # GET /user_twitters/new.json
  def new
    @user_twitter = UserTwitter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_twitter }
    end
  end

  # GET /user_twitters/1/edit
  def edit
    @user_twitter = UserTwitter.find(params[:id])
  end

  # POST /user_twitters
  # POST /user_twitters.json
  def create
    @user_twitter = UserTwitter.new(params[:user_twitter])

    respond_to do |format|
      if @user_twitter.save
        format.html { redirect_to @user_twitter, notice: 'User twitter was successfully created.' }
        format.json { render json: @user_twitter, status: :created, location: @user_twitter }
      else
        format.html { render action: "new" }
        format.json { render json: @user_twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_twitters/1
  # PUT /user_twitters/1.json
  def update
    @user_twitter = UserTwitter.find(params[:id])

    respond_to do |format|
      if @user_twitter.update_attributes(params[:user_twitter])
        format.html { redirect_to @user_twitter, notice: 'User twitter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_twitters/1
  # DELETE /user_twitters/1.json
  def destroy
    @user_twitter = UserTwitter.find(params[:id])
    @user_twitter.destroy

    respond_to do |format|
      format.html { redirect_to user_twitters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_twitters_helper.rb
module UserTwittersHelper
end

app/views/user_twitters/_form.html.haml
<%= form_for(@user_twitter) do |f| %>
  <% if @user_twitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_twitter.errors.count, "error") %> prohibited this user_twitter from being saved:</h2>

      <ul>
      <% @user_twitter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :twitter_token %><br />
    <%= f.text_field :twitter_token %>
  </div>
  <div class="field">
    <%= f.label :twitter_secret_token %><br />
    <%= f.text_field :twitter_secret_token %>
  </div>
  <div class="field">
    <%= f.label :public_token %><br />
    <%= f.text_field :public_token %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.number_field :uid %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_twitters/_item.html.haml
%li{:id => "li_element_#{user_twitter.id}"}
  = image_tag(user_twitter.image_url, :style => 'float: left; margin-right: 10px;')
  %h4=user_twitter.username
  %p
    %span
  %username
    = link_to '', user_twitter, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :"data-replace" => '.portfolio_sidebar.portfolio_sidebar_right', :class => 'delete', :alt => 'Effacer ce compte twitter'

app/views/user_twitters/edit.html.haml
<h1>Editing user_twitter</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_twitter %> |
<%= link_to 'Back', user_twitters_path %>

app/views/user_twitters/index.html.haml
.breadcrumb
  %ul
    %li
      = link_to t('header.menu.dashboard'), dashboard_url(:src => 'ajax'), :remote => true, :onclick => "$('#tabs ul li').removeClass('active');$('#tabs ul li:first').addClass('active');", :"data-replace" => '.portfolio_sidebar.portfolio_sidebar_right'
    %li
      = t('header.menu.twitter_account')
.featuresx_block
  %h5(style='float:right')
    = link_to t("user_twitters.add_twitter"), omniauth_authorize_path(User, 'twitter'), :class => 'btn_l' if current_user.can_add_account
  %h1
    = t('header.menu.twitter_account')
  %ul
    - @user_twitters.each do |user_twitter|
      = render :partial => 'item', :locals => {:user_twitter => user_twitter}

app/views/user_twitters/new.html.haml
<h1>New user_twitter</h1>

<%= render 'form' %>

<%= link_to 'Back', user_twitters_path %>

app/views/user_twitters/show.html.haml
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_twitter.user %>
</p>

<p>
  <b>Username:</b>
  <%= @user_twitter.username %>
</p>

<p>
  <b>Twitter token:</b>
  <%= @user_twitter.twitter_token %>
</p>

<p>
  <b>Twitter secret token:</b>
  <%= @user_twitter.twitter_secret_token %>
</p>

<p>
  <b>Public token:</b>
  <%= @user_twitter.public_token %>
</p>

<p>
  <b>Provider:</b>
  <%= @user_twitter.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @user_twitter.uid %>
</p>

<p>
  <b>Image url:</b>
  <%= @user_twitter.image_url %>
</p>


<%= link_to 'Edit', edit_user_twitter_path(@user_twitter) %> |
<%= link_to 'Back', user_twitters_path %>