config/routes.rb
Misesajour::Application.routes.draw do
  resources :followers

  get 'paypal/success' => 'private#paypal_ok'
  get 'paypal/failed' => 'private#paypal_failed'

  resources :rt_twitts, :only => [:show, :create, :new, :update]

  get "dashboard" => "private#dashboard", :as => :dashboard

  resources :user_twitters

  resources :rss_items

  resources :rss_providers

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}, path: ''
  get "pricing" => 'public#pricing', :as => :pricing_en
  get "tarifs"  => 'public#pricing', :as => :pricing_fr
  root :to => 'public#index'
  match "*a" => redirect('/')
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user_twitter
  attr_accessible :follow_request_send, :followers_count, :following, :friends_count, :twitter_id, :lang, :last_tweet_date, :name, :screen_name, :status_count, :url, :follow_user

  validates_uniqueness_of :twitter_id, :scope => [:user_twitter_id]
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followers }
    end
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
    @follower = Follower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/new
  # GET /followers/new.json
  def new
    @follower = Follower.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/1/edit
  def edit
    @follower = Follower.find(params[:id])
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(params[:follower])

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render json: @follower, status: :created, location: @follower }
      else
        format.html { render action: "new" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /followers/1
  # PUT /followers/1.json
  def update
    @follower = Follower.find(params[:id])

    respond_to do |format|
      if @follower.update_attributes(params[:follower])
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower = Follower.find(params[:id])
    @follower.destroy

    respond_to do |format|
      format.html { redirect_to followers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_twitter %><br />
    <%= f.text_field :user_twitter %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br />
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :followers_count %><br />
    <%= f.number_field :followers_count %>
  </div>
  <div class="field">
    <%= f.label :friends_count %><br />
    <%= f.number_field :friends_count %>
  </div>
  <div class="field">
    <%= f.label :status_count %><br />
    <%= f.number_field :status_count %>
  </div>
  <div class="field">
    <%= f.label :lang %><br />
    <%= f.text_field :lang %>
  </div>
  <div class="field">
    <%= f.label :last_tweet_date %><br />
    <%= f.datetime_select :last_tweet_date %>
  </div>
  <div class="field">
    <%= f.label :following %><br />
    <%= f.check_box :following %>
  </div>
  <div class="field">
    <%= f.label :follow_request_send %><br />
    <%= f.check_box :follow_request_send %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<h1>Listing followers</h1>

<table>
  <tr>
    <th>User twitter</th>
    <th>Id</th>
    <th>Name</th>
    <th>Screen name</th>
    <th>Url</th>
    <th>Followers count</th>
    <th>Friends count</th>
    <th>Status count</th>
    <th>Lang</th>
    <th>Last tweet date</th>
    <th>Following</th>
    <th>Follow request send</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @followers.each do |follower| %>
  <tr>
    <td><%= follower.user_twitter %></td>
    <td><%= follower.id %></td>
    <td><%= follower.name %></td>
    <td><%= follower.screen_name %></td>
    <td><%= follower.url %></td>
    <td><%= follower.followers_count %></td>
    <td><%= follower.friends_count %></td>
    <td><%= follower.status_count %></td>
    <td><%= follower.lang %></td>
    <td><%= follower.last_tweet_date %></td>
    <td><%= follower.following %></td>
    <td><%= follower.follow_request_send %></td>
    <td><%= link_to 'Show', follower %></td>
    <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
    <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User twitter:</b>
  <%= @follower.user_twitter %>
</p>

<p>
  <b>Id:</b>
  <%= @follower.id %>
</p>

<p>
  <b>Name:</b>
  <%= @follower.name %>
</p>

<p>
  <b>Screen name:</b>
  <%= @follower.screen_name %>
</p>

<p>
  <b>Url:</b>
  <%= @follower.url %>
</p>

<p>
  <b>Followers count:</b>
  <%= @follower.followers_count %>
</p>

<p>
  <b>Friends count:</b>
  <%= @follower.friends_count %>
</p>

<p>
  <b>Status count:</b>
  <%= @follower.status_count %>
</p>

<p>
  <b>Lang:</b>
  <%= @follower.lang %>
</p>

<p>
  <b>Last tweet date:</b>
  <%= @follower.last_tweet_date %>
</p>

<p>
  <b>Following:</b>
  <%= @follower.following %>
</p>

<p>
  <b>Follow request send:</b>
  <%= @follower.follow_request_send %>
</p>


<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>