config/routes.rb
Misesajour::Application.routes.draw do
  resources :followers

  get 'paypal/success' => 'private#paypal_ok'
  get 'paypal/failed' => 'private#paypal_failed'

  resources :rt_twitts, :only => [:show, :create, :new, :update]

  get "dashboard" => "private#dashboard", :as => :dashboard

  resources :user_twitters

  resources :rss_items

  resources :rss_providers

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}, path: ''
  get "pricing" => 'public#pricing', :as => :pricing_en
  get "tarifs"  => 'public#pricing', :as => :pricing_fr
  root :to => 'public#index'
  match "*a" => redirect('/')
end

app/views/layouts/_footer.html.haml
.social_block
  .wraper
    %p
      = t('footer.slogan')
    %ul
      %li.twitter
        = link_to "Twitter", 'http://twitter.com/misesajourCom'
- render :partial => 'layouts/footer_line'
.copyright
  .wraper
    %p
      %span> Copyright 2012 miseajour.net
    %a.top{:href => "#"}
      = t('footer.go_top')

app/views/layouts/_footer_line.html.haml
.footer
  %footer
    / bottom about
    .bottom_about
      %p
        %img{:alt => "", :src => "/assets/logo.png"}/
      %p At vero eos et accusaus et iusto unir un dignissimos ducimus quirds siter ters pi blranditiis praesentium amets voluptatum un deleniti atque corrupti quosdirs dolores etra quasir moltias unstw excepturi sinte amets occaecatires.
    / /bottom about
    / recent tweets
    .recent_tweets
      %h3
        %span Recent Tweets
      %ul
        %li
          %a{:href => "#"} @laurakalbag
          I will be very soon. Ase result reco endation
          %a{:href => "#"} 31 minutes ago
        %li
          %a{:href => "#"} @laurakalbag
          you got chocolates!? That's i I'm signing up.
          %a{:href => "#"} 37 minutes ago
    / /recent tweets
    / recent posts
    .recent_posts
      %h3
        %span Recent Posts
      %ul
        %li
          %a{:href => "#"} Lorem ipsum dolo amet consecect
        %li
          %a{:href => "#"} Sed laoreet neque nonte mauris
        %li
          %a{:href => "#"} Metus lacus, porta vestibulum
        %li
          %a{:href => "#"} Morbi ac magna est ornare eliticits
        %li
          %a{:href => "#"} Voluptas sadips nemis un etras
    / /recent posts
    / subscribe block
    .subscribe_block
      %h3
        %span Stay Connected
      %form{:action => "#", :method => "post"}
        %p
          %input#name{:type => "text", :value => "NAME ..."}/
        %p
          %input#email{:type => "text", :value => "EMAIL ..."}/
        %p
          %input{:type => "submit", :value => "Subscribe"}/
    / /subscribe block

app/views/layouts/_google.en.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-18454595-2']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/_google.fr.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-18454595-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/_header.html.haml
%header.header
  = link_to "Misesajour", root_url, :class => 'logo'
  %strong
    = t('slogan')
  %nav
    %ul
      - if current_user
        %li
          = link_to t('header.menu.dashboard'), dashboard_url
      - else
        %li
          = link_to t('header.menu.home'), root_url
      %li
        = link_to t('header.menu.pricing'), ( I18n.locale.to_s == 'fr' ? pricing_fr_path() : pricing_en_path())
      - if current_user
        %li
          = link_to t('header.menu.logout'), destroy_user_session_path, :method => :delete

      - else
        - User.omniauth_providers.each do |provider|
          %li
            = link_to t('header.menu.sign_in'), omniauth_authorize_path(User, provider)
      - if request.subdomains.first=='en'
        %li
          = link_to t('header.menu.french'), 'http://www.misesajour.com'
      - else
        %li
          = link_to t('header.menu.english'), 'http://en.misesajour.com'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
    %meta{:content => content_for?(:description) ? yield(:description) : t('index.description'), :name => "description"}/
    %title
      = content_for?(:title) ? yield(:title) : t('index.title')
    %link{:href => "/assets/favicon.ico", :rel => "icon", :type => "image/png"}/
    %link{:href => "/assets/apple-touch-icon.png", :rel => "apple-touch-icon"}
    %link{:href => "/assets/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
    %link{:href => "/assets/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}
    /[if lt IE 9]
      <script src="scripts/ie9.js">IE7_PNG_SUFFIX=".png";</script>
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = render :partial => 'layouts/google'
    = csrf_meta_tags
    :javascript
      $(function(){
          $('#obo_slider').oneByOne({
              className: 'oneByOne1',
              easeType: 'random',
              slideShow: true
          });

      })

  %body
    .wraper
      = render :partial => 'layouts/header'
    = yield
    = render :partial => 'layouts/footer'

app/views/layouts/private.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
    %title Home
    %link{:href => "/assets/favicon.ico", :rel => "icon", :type => "image/png"}/
    %link{:href => "/assets/apple-touch-icon.png", :rel => "apple-touch-icon"}
    %link{:href => "/assets/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
    %link{:href => "/assets/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}
    /[if lt IE 9]
      <script src="scripts/ie9.js">IE7_PNG_SUFFIX=".png";</script>
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:400,400italic,700,700italic", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = render :partial => 'layouts/google'
    = csrf_meta_tags
    :javascript
      $(function(){
          $('#obo_slider').oneByOne({
              className: 'oneByOne1',
              easeType: 'random',
              slideShow: true
          });

      })

  %body
    .wraper
      = render :partial => 'layouts/header'
    .content_block
      .top_title
        .wraper
          %h2
            = t('private.welcome')
            = "#{current_user.user_twitters.first.username}"
            %span
              = t('private.slogan')
      .wraper
        .sidebar
          .left_nav
            #tabs
              %ul.tab_select
                %li.active
                  = link_to t('header.menu.dashboard'), dashboard_url(:src => 'ajax'), :remote => true, :"data-replace" => '.portfolio_sidebar.portfolio_sidebar_right'
                %li
                  = link_to t('header.menu.rss_sitemap'), rss_providers_url(:src => 'ajax'), :remote => true, :"data-replace" => '.portfolio_sidebar.portfolio_sidebar_right'
                %li
                  = link_to t('header.menu.twitter_account'), user_twitters_url(:src => 'ajax'), :remote => true, :"data-replace" => '.portfolio_sidebar.portfolio_sidebar_right'
        .portfolio_sidebar.portfolio_sidebar_right
          = yield
    = render :partial => 'layouts/footer'